# Generated by Django 4.2.7 on 2023-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0003_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_monthly_files',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_monthly_projects',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_monthly_users',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_yearly_files',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_yearly_projects',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_yearly_users',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='summary',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='total_projects',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='total_users',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
