# Generated by Django 4.2.7 on 2023-12-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0004_remove_summary_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
