# Generated by Django 4.2.7 on 2023-12-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_delete_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monthly_projects', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_monthly_users', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_monthly_files', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_monthly_sites', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_annual_projects', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_annual_users', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_annual_files', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_annual_sites', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
