# Generated by Django 4.2.7 on 2023-12-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0006_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='total_annual_sites',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='total_monthly_sites',
        ),
    ]
