# Generated by Django 4.2.7 on 2023-12-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='document',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='project_name',
        ),
    ]
